### ISSUE TITLE
now, missed twi share

### ISSUE THREAD

**Issue by alundiak** [fliptheweb/motion-ui-design#1]
![image](https://cloud.githubusercontent.com/assets/2131633/12531376/205fa8da-c1f9-11e5-94bd-4437318d7c5d.png)

**Comment by fliptheweb** [comment]
@alundiak thank you! I changed markdown links to html link, cuz markdown don't accept link attributes, can you check it agan?
P.S. Congratulations, you're make first issue! 🎉

**Comment by alundiak** [comment]
Issue the same.
But generated code looks correct:

```
<ul>
<li><a href="https://twitter.com/intent/tweet?text=https://github.com/fliptheweb/motion-ui-design%20Motion%20UI%20Design%20collection" target="_blank">Share on Twitter</a></li>
<li><a href="https://www.facebook.com/sharer/sharer.php?s=100&amp;p[url]=https://github.com/fliptheweb/motion-ui-design&amp;p[images][0]=&amp;p[title]=Motion%20UI%20Design%20Collection&amp;p[summary]=" target="_blank">Share on Facebook</a></li>
</ul>
```

But u must not use A element/tag in md file.

**Comment by alundiak** [comment]
:) Change code back to markdown (it should work - I will re-test). It was my AdsBlocker. But interesting, that on twitter was locked.

**Comment by fliptheweb** [comment]
Markdown accept some subset of HTML https://help.github.com/articles/github-flavored-markdown/#html
Ooops :) My Chrome AdBlock don't block that link, interesting,
But anyway thank you for reporting!
